handle multiple function calls
pipecat-ai/pipecat pull request #346
Opened 2024-08-07 07:42 UTC by jeevan057

openai can give multiple tool calls 
ex : "message": {
                "role": "assistant",
                "content": null,
                "tool_calls": [
                    {
                        "id": "call_cuC7cq3IoIqCN2IvwfGuNl8J",
                        "type": "function",
                        "function": {
                            "name": "add_numbers",
                            "arguments": "{\"a\": 1, \"b\": 2}"
                        }
                    },
                    {
                        "id": "call_SfbHakQINYSeK9a7VzQq50OW",
                        "type": "function",
                        "function": {
                            "name": "add_numbers",
                            "arguments": "{\"a\": 3, \"b\": 4}"
                        }
                    }
                ],
                "refusal": null
            },
            
  The current implementation assumes only single function call. In this case we get function name as add_numbersadd_numbers (here we have function name twice ).  This would fail when the openai is giving multiple tool calls.
  
  The fix I used is create a list of function names and call them.

2024-08-08 23:56 UTC, aconchillo commented
This is awesome. Thank you! @chadbailey59 what do you think?

2024-08-09 11:12 UTC, cartesis07 commented
Great thanks!

2024-09-07 19:02 UTC, szeka94 commented
any concerns merging this? I'm running into the same error.

2024-09-30 01:24 UTC, kwindla requested changes
This is great! Just needs one tiny fix.

2024-09-30 01:24 UTC, kwindla commented on src/pipecat/services/openai.py
> +                    await self._handle_function_call(context, tool_call_id, function_name, arguments)
The argument here should be `tool_id` not `tool_call_id`.

2024-09-30 01:41 UTC, kwindla commented
Oof. Enough stuff has changed out from under this PR that there needs to be some more code in the context aggregator to make this work, now.

I'll figure this out tonight and post another PR.

Thank you for doing the work, here ... we'll get this into the next Pipecat release!

2024-09-30 23:25 UTC, kwindla commented
Merged as this PR: https://github.com/pipecat-ai/pipecat/pull/522

2024-09-30 23:25 UTC, closed without merging