simplify token example
pipecat-ai/pipecat pull request #630
Opened 2024-10-20 22:29 UTC by MoofSoup

2 hackers at the hackathon were confused by this line, and interpreted token as api key

2024-10-21 23:36 UTC, vipyne commented on README.md
> +    token="", # leave empty, token is not api key
```suggestion
    token="", # leave empty. Note: token is _not_ api key
```

2024-10-21 23:37 UTC, vipyne requested changes
thank you @MoofSoup !  can you prepend the commits with `docs: ` please?  (feel free to squash them to one commit as well if that is easy)

2024-10-22 02:59 UTC, MoofSoup commented
Hey! I updated the pr! Let me know if this works!

2024-10-26 01:50 UTC, MoofSoup commented
hey @vipyne just following up on this!

2024-10-28 15:23 UTC, vipyne commented
awesome.  thank you @MoofSoup !

2024-10-28 15:26 UTC, merged